<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Weld.Physics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Weld.World\Weld.World.csproj" />
  </ItemGroup>

</Project>
